//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoGoService.DataObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DogoDbEntities : DbContext
    {
        public DogoDbEntities()
            : base("name=DogoDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilityTime> AvailabilityTimes { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<UserRequest> UserRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Walker> Walkers { get; set; }
    }
}
