//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoGoService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogWalker
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public bool isComfortable6To8 { get; set; }
        public bool isComfortable8To10 { get; set; }
        public bool isComfortable10To12 { get; set; }
        public bool isComfortable12To14 { get; set; }
        public bool isComfortable14To16 { get; set; }
        public bool isComfortable16To18 { get; set; }
        public bool isComfortable18To20 { get; set; }
        public bool isComfortable20To22 { get; set; }
        public int age { get; set; }
        public int priceForHour { get; set; }
    }
}
