//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoGoService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequest
    {
        public int id { get; set; }
        public Nullable<int> requestingUserId { get; set; }
        public Nullable<int> requestedUserId { get; set; }
        public string status { get; set; }
    
        public virtual User requestingUser { get; set; }
        public virtual User requestedUser { get; set; }
    }
}
