//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoGoService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequest
    {
        public int Id { get; set; }
        public Nullable<int> RequestingUserId { get; set; }
        public Nullable<int> RequestedUserId { get; set; }
        public string Status { get; set; }
    }
}
